language: node_js
cache: yarn
node_js:
  - "10"
  - node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
# run install twice. flaky npm behavior
# https://github.com/GitbookIO/gitbook/issues/1834
script: yarn test

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - yarn build

jobs:
  include:
    - stage: npm
      node_js: "10"
      deploy:
          provider: script
          script: "yarn run publish"
          skip_cleanup: true
          on:
            tags: true
    - stage: docs
      script: yarn docs:prepare && yarn docs:build
      node_js: "10"
      deploy:
        provider: pages
        local-dir: hygen.io/public
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        keep-history: true
    - stage: binary releases
      script: yarn standalone
      node_js: "10"
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: standalone/*
        skip_cleanup: true
        on:
          tags: true
